# Generated by Django 4.1.10 on 2023-07-25 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('fld_money_id', models.AutoField(primary_key=True, serialize=False)),
                ('fld_value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fld_description', models.TextField(default='')),
                ('fld_type', models.CharField(choices=[('a', 'add'), ('m', 'minus')], max_length=5)),
                ('fld_date_added', models.DateTimeField(auto_now_add=True)),
                ('fld_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ipon',
            fields=[
                ('fld_ipon_id', models.AutoField(primary_key=True, serialize=False)),
                ('fld_ipon', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fld_ipon_desc', models.TextField()),
                ('fld_money_per_day', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fld_target_date', models.DateTimeField(auto_now_add=True)),
                ('fld_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
