# Generated by Django 4.1.10 on 2023-07-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipon',
            name='fld_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='money',
            name='fld_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
