# Generated by Django 4.1.10 on 2023-07-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_main', '0002_ipon_fld_title_money_fld_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='fld_date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
