# Generated by Django 4.1.10 on 2023-07-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_main', '0003_alter_money_fld_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipon',
            name='fld_money_per_day',
        ),
        migrations.RemoveField(
            model_name='ipon',
            name='fld_target_date',
        ),
    ]
